### ISSUE TITLE
perm&enchants

### ISSUE THREAD

**Issue by UnendingApple** [Taylcd/Kit#1]
I am not a developer so I cant just fork your plugin and add this myself, 
I was wondering if you could tell me how to add enchants to kits, also could you add permissions for just 1 kit such as "kit.permission.(namekit)" please find me on twitter, discord, skype...
Twitter- @UnendingApple

Discord- Apple#7065

Skype- Unending Apple

THANKS!

**Comment by Taylcd** [comment]
When you add an item in the config file, it should be like this:
```
id:meta:amount:enchantId:enchantLevel
```
Also, permissions was planned to be improved in the next version of the plugin, and permissions like that will be supported.

**Comment by UnendingApple** [comment]
when are you planning the new update?

**Comment by Taylcd** [comment]
When I’m available.

**Comment by UnendingApple** [comment]
ok
